/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumslist;

import Conexao.DBController;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author laura
 */
public class AlbumList extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioOpcao
     */
    public AlbumList() {
        initComponents();
    }
    
    public void generateReport(String file) {  
        try {
            DBController db = new DBController();
            JasperReport report = (JasperReport) 
                    JRLoader.loadObjectFromFile(file);

            db.conectar();
            JasperPrint printReport = JasperFillManager.fillReport(report,
                null, db.getConexao());
            db.desconectar();

            JasperViewer showReport = new JasperViewer(printReport);
            showReport.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            showReport.setTitle("Meus álbuns");
            showReport.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        btnAlbumsList = new javax.swing.JButton();
        btnAlbumsListDetailed = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Suas listas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPageTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPageTitle.setText("Escolha uma das opções:");

        btnAlbumsList.setBackground(new java.awt.Color(255, 255, 255));
        btnAlbumsList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAlbumsList.setText("Lista dos álbuns preferidos");
        btnAlbumsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumsListActionPerformed(evt);
            }
        });

        btnAlbumsListDetailed.setBackground(new java.awt.Color(255, 255, 255));
        btnAlbumsListDetailed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAlbumsListDetailed.setText("Lista dos álbuns completa");
        btnAlbumsListDetailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlbumsListDetailedActionPerformed(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Voltar");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPageTitle)
                            .addComponent(btnGoBack))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 85, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlbumsList)
                            .addComponent(btnAlbumsListDetailed))
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblPageTitle)
                .addGap(43, 43, 43)
                .addComponent(btnAlbumsList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlbumsListDetailed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnGoBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlbumsListDetailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumsListDetailedActionPerformed
        String albumsListDetailed = "C:\\Users\\laura\\Documents\\NetBeansProjects\\"
                + "ListaDeAlbuns\\src\\main\\reports"
                + "\\album_list_detailed\\album_list_detailed(1).jasper";
        generateReport(albumsListDetailed);
    }//GEN-LAST:event_btnAlbumsListDetailedActionPerformed

    private void btnAlbumsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlbumsListActionPerformed
        String albumsList = "C:\\Users\\laura\\Documents\\NetBeansProjects\\"
        + "ListaDeAlbuns\\src\\main\\reports\\album_list\\album_list.jasper";
        generateReport(albumsList);
    }//GEN-LAST:event_btnAlbumsListActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlbumList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbumsList;
    private javax.swing.JButton btnAlbumsListDetailed;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPageTitle;
    // End of variables declaration//GEN-END:variables
}
