/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumslist;

import java.util.HashMap;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author laura
 */
public class Ranking extends javax.swing.JFrame {
    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        showRanking();
    }
    
    public void showRanking() {
        List<Album> albums;
        HashMap<String, String> artistAndTheirQuantities = new HashMap<>();
        int firstPlaceAlbumsQnt = 0;
        int secondPlaceAlbumsQnt = 0;
        int thirdPlaceAlbumsQnt = 0;
        String firstPlaceArtist = "";
        String secondPlaceArtist = "";
        String thirdPlaceArtist = "";
        int qnt;
            
        try {
            albums = Album.searchAlbums();
            for (int i = 0; i < albums.size(); i++) {
                qnt = 0;
                for (int y = 0; y < albums.size(); y++) {
                    if (albums.get(i).getArtistName()
                            .equals(albums.get(y).getArtistName())) {
                        qnt++;
                        artistAndTheirQuantities.
                                put(albums.get(i).getArtistName(), String.valueOf(qnt));
                    }
                }
            }
            
            for (String name : artistAndTheirQuantities.keySet()) {
                qnt = Integer.parseInt(artistAndTheirQuantities.get(name));
                
                if (qnt > firstPlaceAlbumsQnt) {
                    firstPlaceAlbumsQnt = qnt;
                    firstPlaceArtist = name;
                } else if (qnt < firstPlaceAlbumsQnt && (qnt > thirdPlaceAlbumsQnt)
                        && qnt != secondPlaceAlbumsQnt) {
                    secondPlaceAlbumsQnt = qnt;
                    secondPlaceArtist = name;
                } else {
                    thirdPlaceAlbumsQnt = qnt;
                    thirdPlaceArtist = name;
                }
            }
            
            showFirstArtist(firstPlaceArtist, firstPlaceAlbumsQnt);
            showSecondArtist(secondPlaceArtist, secondPlaceAlbumsQnt);
            showThirdArtist(thirdPlaceArtist, thirdPlaceAlbumsQnt);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void showFirstArtist(String artist, int qnt) {
        showInfo(lblNumberOne, lblFirstArtistName, artist, qnt);
    }
    
    public void showSecondArtist(String artist, int qnt) {
        showInfo(lblNumberTwo, lblSecondArtistName, artist, qnt);
    }
    
    public void showThirdArtist(String artist, int qnt) {
        showInfo(lblNumberThree, lblThirdArtistName, artist, qnt);
    }
    
    public void showInfo(JLabel place, JLabel lblArtist, String artist, int qnt) {
        switch (qnt) {
            case 0:
                place.setVisible(false);
                break;
            case 1:
                lblArtist.setText(artist.toUpperCase() + ", " + qnt + " álbum");
                break;
            default:
                lblArtist.setText(artist.toUpperCase() + ", " + qnt + " álbuns");
                break;
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGoBack = new javax.swing.JButton();
        lblNumberOne = new javax.swing.JLabel();
        lblNumberTwo = new javax.swing.JLabel();
        lblFirstArtistName = new javax.swing.JLabel();
        lblSecondArtistName = new javax.swing.JLabel();
        lblThirdArtistName = new javax.swing.JLabel();
        lblNumberThree = new javax.swing.JLabel();
        lblPageTitle = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ranking");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnGoBack.setBackground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Voltar");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblNumberOne.setFont(new java.awt.Font("Noto Sans Light", 3, 80)); // NOI18N
        lblNumberOne.setText("1");

        lblNumberTwo.setFont(new java.awt.Font("Noto Sans Light", 3, 60)); // NOI18N
        lblNumberTwo.setText("2");

        lblFirstArtistName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblSecondArtistName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblThirdArtistName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblNumberThree.setFont(new java.awt.Font("Noto Sans Light", 3, 40)); // NOI18N
        lblNumberThree.setText("3");

        lblPageTitle.setFont(new java.awt.Font("Noto Sans Light", 1, 24)); // NOI18N
        lblPageTitle.setText("Meus artistas preferidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPageTitle)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNumberOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumberTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumberThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstArtistName)
                            .addComponent(lblSecondArtistName)
                            .addComponent(lblThirdArtistName))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblPageTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblFirstArtistName))
                    .addComponent(lblNumberOne))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumberTwo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblSecondArtistName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberThree)
                    .addComponent(lblThirdArtistName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnGoBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFirstArtistName;
    private javax.swing.JLabel lblNumberOne;
    private javax.swing.JLabel lblNumberThree;
    private javax.swing.JLabel lblNumberTwo;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSecondArtistName;
    private javax.swing.JLabel lblThirdArtistName;
    // End of variables declaration//GEN-END:variables
}
