/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumslist;

import javax.swing.ImageIcon;

/**
 *
 * @author laura
 */
public class AlbumInfo extends javax.swing.JFrame {
    Album album;
    /**
     * Creates new form AlbumInfo
     */
    public AlbumInfo() {
        initComponents();
    }
    
    public AlbumInfo(Album album) {
        initComponents();
        setAlbum(album);
        showInfo();
    }

    public Album getAlbum() {
        return this.album;
    }

    public void setAlbum(Album album) {
        this.album = album;
    }
    
    public void showInfo() {
        lblAlbumName.setText(this.getAlbum().getName());
        lblArtistName.setText(this.getAlbum().getArtistName());
        lblDebutYear.setText(String.valueOf(this.getAlbum().getDebutYear()));
        lblSongsNumber.setText(String.valueOf(this.getAlbum().getSongsNumber()));
        lblDuration.setText(this.getAlbum().toString());
        ImageIcon albumCover = new ImageIcon(this.getAlbum().getCover());
        lblAlbumCover.setIcon(albumCover);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAlbumCover = new javax.swing.JLabel();
        lblIndicatorAlbumName = new javax.swing.JLabel();
        lblIndicatorArtistName = new javax.swing.JLabel();
        lblIndicatorDebutYear = new javax.swing.JLabel();
        lblIndicatorSongsNumber = new javax.swing.JLabel();
        lblIndicatorDuration = new javax.swing.JLabel();
        lblAlbumName = new javax.swing.JLabel();
        lblArtistName = new javax.swing.JLabel();
        lblDebutYear = new javax.swing.JLabel();
        lblSongsNumber = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Álbum info");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblIndicatorAlbumName.setFont(new java.awt.Font("Noto Sans Light", 1, 14)); // NOI18N
        lblIndicatorAlbumName.setText("NOME:");

        lblIndicatorArtistName.setFont(new java.awt.Font("Noto Sans Light", 1, 14)); // NOI18N
        lblIndicatorArtistName.setText("ARTISTA:");

        lblIndicatorDebutYear.setFont(new java.awt.Font("Noto Sans Light", 1, 14)); // NOI18N
        lblIndicatorDebutYear.setText("ANO DE LANÇAMENTO:");

        lblIndicatorSongsNumber.setFont(new java.awt.Font("Noto Sans Light", 1, 14)); // NOI18N
        lblIndicatorSongsNumber.setText("Nº DE FAIXAS:");

        lblIndicatorDuration.setFont(new java.awt.Font("Noto Sans Light", 1, 14)); // NOI18N
        lblIndicatorDuration.setText("DURAÇÃO:");

        lblAlbumName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblArtistName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDebutYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblSongsNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDuration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnGoBack.setBackground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Voltar");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIndicatorAlbumName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAlbumName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIndicatorArtistName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblArtistName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIndicatorSongsNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSongsNumber))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIndicatorDuration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDuration))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIndicatorDebutYear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDebutYear)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 158, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAlbumCover)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGoBack)
                                .addGap(158, 158, 158))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAlbumCover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndicatorAlbumName)
                    .addComponent(lblAlbumName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndicatorArtistName)
                    .addComponent(lblArtistName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndicatorDebutYear)
                    .addComponent(lblDebutYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndicatorSongsNumber)
                    .addComponent(lblSongsNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndicatorDuration)
                    .addComponent(lblDuration))
                .addGap(17, 17, 17)
                .addComponent(btnGoBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_btnGoBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlbumInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlbumCover;
    private javax.swing.JLabel lblAlbumName;
    private javax.swing.JLabel lblArtistName;
    private javax.swing.JLabel lblDebutYear;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblIndicatorAlbumName;
    private javax.swing.JLabel lblIndicatorArtistName;
    private javax.swing.JLabel lblIndicatorDebutYear;
    private javax.swing.JLabel lblIndicatorDuration;
    private javax.swing.JLabel lblIndicatorSongsNumber;
    private javax.swing.JLabel lblSongsNumber;
    // End of variables declaration//GEN-END:variables
}
