/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package albumslist;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author laura
 */
public class UpdateAlbum extends javax.swing.JFrame {
    private Album album;
    private Color lblColor;
    
    /**
     * Creates new form AlteraAlbum
     */
    
    public UpdateAlbum() {
        initComponents();
    }
    
    public UpdateAlbum(Album album, Color lblColor) {
        initComponents();
        setAlbum(album);
        setLblColor(lblColor);
        showInfo();
    }

    public Album getAlbum() {
        return this.album;
    }

    public void setAlbum(Album album) {
        this.album = album;
    }

    public Color getLblColor() {
        return this.lblColor;
    }

    public void setLblColor(Color lblColor) {
        this.lblColor = lblColor;
    }
    
    public void showInfo() {
        lblAlbumTitle.setText(this.getAlbum().getName());
        lblAlbumTitle.setForeground(this.getLblColor());
        tfAlbumName.setText(this.getAlbum().getName());
        tfArtistName.setText(this.getAlbum().getArtistName());
        tfDebutYear.setText(String.valueOf(this.getAlbum().getDebutYear()));
        tfSongsNumber.setText(String.valueOf(this.getAlbum().getSongsNumber()));
        tfMinutes.setText(String.valueOf(this.getAlbum().getDuration().getMinutes()));
        tfSeconds.setText(String.valueOf(this.getAlbum().getDuration().getSeconds()));
        tfAlbumCover.setText(this.getAlbum().getCover());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcAlbumCover = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        lblPageTitle = new javax.swing.JLabel();
        lblAlbumName = new javax.swing.JLabel();
        lblArtistName = new javax.swing.JLabel();
        tfAlbumName = new javax.swing.JTextField();
        tfArtistName = new javax.swing.JTextField();
        lblSongsNumber = new javax.swing.JLabel();
        lblDebutYear = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        tfSongsNumber = new javax.swing.JTextField();
        tfDebutYear = new javax.swing.JTextField();
        lblDurationMin = new javax.swing.JLabel();
        tfMinutes = new javax.swing.JTextField();
        lblDurationSec = new javax.swing.JLabel();
        tfSeconds = new javax.swing.JTextField();
        lblAlbumCover = new javax.swing.JLabel();
        btnSelectImage = new javax.swing.JButton();
        tfAlbumCover = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblAlbumTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Álbum");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPageTitle.setFont(new java.awt.Font("Noto Sans Light", 1, 18)); // NOI18N
        lblPageTitle.setText("Alterar");

        lblAlbumName.setText("Nome do álbum:");

        lblArtistName.setText("Nome da(o) artista:");

        lblSongsNumber.setText("Nº de faixas:");

        lblDebutYear.setText("Ano de lançamento:");

        lblDuration.setText("Duração:");

        lblDurationMin.setText("min");

        lblDurationSec.setText("seg");

        lblAlbumCover.setText("Capa:");

        btnSelectImage.setBackground(new java.awt.Color(255, 255, 255));
        btnSelectImage.setText("Inserir imagem");
        btnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImageActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Atualizar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblAlbumTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblPageTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlbumTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAlbumName)
                        .addGap(196, 196, 196)
                        .addComponent(lblArtistName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tfAlbumName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblSongsNumber)
                        .addGap(43, 43, 43)
                        .addComponent(lblDebutYear)
                        .addGap(71, 71, 71)
                        .addComponent(lblDuration))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tfDebutYear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSongsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lblDurationMin)
                        .addGap(4, 4, 4)
                        .addComponent(tfMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(lblDurationSec)
                        .addGap(4, 4, 4)
                        .addComponent(tfSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAlbumCover)
                        .addGap(4, 4, 4)
                        .addComponent(btnSelectImage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tfAlbumCover, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(btnCancel)
                        .addGap(6, 6, 6)
                        .addComponent(btnEdit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPageTitle)
                    .addComponent(lblAlbumTitle))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlbumName)
                    .addComponent(lblArtistName))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAlbumName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSongsNumber)
                    .addComponent(lblDebutYear)
                    .addComponent(lblDuration))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDebutYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSongsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDurationMin))
                    .addComponent(tfMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDurationSec))
                    .addComponent(tfSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblAlbumCover))
                    .addComponent(btnSelectImage))
                .addGap(6, 6, 6)
                .addComponent(tfAlbumCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            String albumName = tfAlbumName.getText();
            String artistName = tfArtistName.getText();
            int debutYear = Integer.parseInt(tfDebutYear.getText());
            int minutes = Integer.parseInt(tfMinutes.getText());
            int seconds = Integer.parseInt(tfSeconds.getText());
            int songsNumber = Integer.parseInt(tfSongsNumber.getText());
            String cover = tfAlbumCover.getText();

            Album album = new Album();

            album.setArtistName(artistName);
            album.setName(albumName);
            album.setDebutYear(debutYear);
            Duration duration = new Duration(minutes, seconds);
            album.setDuration(duration);
            album.setSongsNumber(songsNumber);
            album.setCover(cover.replace("\\", "\\\\"));
            album.addAlbum();

            this.dispose();
            new MainScreen().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImageActionPerformed
        int chooseFile = fcAlbumCover.showOpenDialog(this);
        
        if (chooseFile == JFileChooser.APPROVE_OPTION) {
            File selectedImg = fcAlbumCover.getSelectedFile();
            tfAlbumCover.setText(selectedImg.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelectImageActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSelectImage;
    private javax.swing.JFileChooser fcAlbumCover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlbumCover;
    private javax.swing.JLabel lblAlbumName;
    private javax.swing.JLabel lblAlbumTitle;
    private javax.swing.JLabel lblArtistName;
    private javax.swing.JLabel lblDebutYear;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblDurationMin;
    private javax.swing.JLabel lblDurationSec;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSongsNumber;
    private javax.swing.JTextField tfAlbumCover;
    private javax.swing.JTextField tfAlbumName;
    private javax.swing.JTextField tfArtistName;
    private javax.swing.JTextField tfDebutYear;
    private javax.swing.JTextField tfMinutes;
    private javax.swing.JTextField tfSeconds;
    private javax.swing.JTextField tfSongsNumber;
    // End of variables declaration//GEN-END:variables
}
